### ISSUE TITLE
email-verify returns failure returned when running multiple verifications

### ISSUE THREAD

**Issue by deepakmani** [bighappyworld/email-verify#11]
Hi,

Thanks for this module!
I just wanted to inform you that valid email addresses don't return info.success = true when I run several   verifications in a short time period.
After googling, I saw this SO post:http://stackoverflow.com/questions/21181843/why-is-dns-resolvemx-always-returning-an-error-when-called-many-times

I was wondering if you see this issue and whether we can add a server rotation option for everyone's benefit.

- Deepak

**Comment by bighappyworld** [comment]
If you need this quickly, I'd suggest forking it and doing a pull request. At this point in time, I don't have the time to add this.

If I get some time, I'll see what I can do. It shouldn't be too much trouble.

**Comment by deepakmani** [comment]
Understood. I've not been able to solve the issue due to a bug.
Did you encounter this issue of DNS server blocking the IP after too many
mx queries? I was wondering if herokus dynamic IP system sort of prevents
from being blocked. Also, does it matter what we set for options.sender?

Thanks,
Deepak
