### ISSUE TITLE
Incorrect callback

### ISSUE THREAD

**Issue by Sicria** [bighappyworld/email-verify#12]
On some emails if it throws an error, it returns the callback twice.

Also when it errors, the callback is in the wrong format. Should be `error, info` but is `info, error`.

**Comment by bighappyworld** [comment]
Could you provide a test email where it calls the callback twice?

**Comment by bighappyworld** [comment]
I've put some blocks to prevent the callback from being called twice on an error. Would love it if you tested it. Version 0.0.14 is now published to npm.

**Comment by Sicria** [comment]
I'll test it when I get a chance and report back.

**Comment by Sicria** [comment]
Works great now, thank you.

The error: ``[Error: write after end]``

Still getting the error but the double callback has been fixed.

**Comment by bighappyworld** [comment]
Pushed a patch, want to try it out?

**Comment by Sicria** [comment]
Same result. Here's the email that is causing the issues. 
``kylie@fuseinteriors.com.au``
