### ISSUE TITLE
Some domains are always valid

### ISSUE THREAD

**Issue by chamnap** [bighappyworld/email-verify#14]
Thanks for your awesome library, I have experienced that emails on some domains like `adobe.com` always returns valid no matter what. Do you have any idea how to work on that? At least, return back, with this domain, we cannot do verification. It would be great to have this functionality, you can try on http://www.mailtester.com/ with any emails on `adobe.com`. `mailtester` will return the following:

>
Mail servers found for domain:
- adobe.mail.protection.outlook.com (priority 2, ip address: 207.46.163.215)
- adobe-com.mail.protection.outlook.com (priority 1, ip address: 207.46.163.170)
Using mail server with lowest priority number:
- adobe-com.mail.protection.outlook.com (priority 1, ip address: 207.46.163.215)
Mailserver identification:
BL2FFO11FD023.mail.protection.outlook.com Microsoft ESMTP MAIL Service ready at Fri, 13 Nov 2015 01:10:56 +0000
Server doesn't allow e-mail address verification

**Comment by grantgeorge** [comment]
There are cases in which a server is configured for catch all, see:

https://docs-rtapi.readthedocs.org/en/latest/status-codes.html

> The server is configured for catch all and responds to all email verifications with a status of Ok.

> Mail servers can be configured with a policy known as Catch All. Catch all redirects any email address sent to a particular domain to a central email box for manual inspection. Catch all configured servers cannot respond to requests for email address verification.

One possible check you can make is to test a *very likely* invalid email address, ex: serverisprobablycatchall@example.com. If this test passes, the domain server is probably catch all. If it's catch all, not sure there's much you can do from an smtp server stand point to verify an address.

**Comment by bighappyworld** [comment]
@grantgeorge That makes sense to me. I've seen it a few times but didn't investigate much.

**Comment by chamnap** [comment]
@grantgeorge, thanks for your awesome answer.
