### ISSUE TITLE
not working in yahoo mails. It shows ECONNREFUSED

### ISSUE THREAD

**Issue by avg6003** [bighappyworld/email-verify#17]
```javascript
var verifier = require('email-verify');
verifier.verify( 'dipsi_rai@yahoo.com', function( err, info ){
  if( err ) console.log(err);
  else{
    console.log( "Success (T/F): " + info.success );
    console.log( "Info: " + info.info );
  }
});
```
Email address is valid but is shows invalid email address. I have tried to use port in options with 465 and 587 which didn't work.
In online tool it shows 
```
true
"Success (T/F): false"
"Info: dipsi_rai@yahoo.com is an invalid address"
```
Note: Email address is correct. I have tried other addresses too.

**Comment by bighappyworld** [comment]
Try to use telnet with Yahoo's SMTP server. If you can connect with telnet and send the proper messages and it works, the plugin should work. However, if they have a different setup, perhaps we can add or augment this module.

**Comment by avg6003** [comment]
Thank you for your response. Now I can send the messages through the module. But in browser still it shows that the email address is Invalid. I didn't make any change in my code though.
