### ISSUE TITLE
optimization for big amount

### ISSUE THREAD

**Issue by zh99998** [bighappyworld/email-verify#21]
I'm using this script to verify about 300k email addresses. but only output 2354 records. I'm sure there is many more valid email addresses in list.

**Comment by bighappyworld** [comment]
how did you throttle the requests?

**Comment by zh99998** [comment]
CLI...
```bash
email-verify --file list.txt
```

**Comment by bighappyworld** [comment]
making 300k simultaneous request to an email server probably isn't a good idea. if you'd like to implement a throttling mechanism for the file option that would be wonderful. i'll send a message to the guy who implemented the file option and see if he has time to add it.

**Comment by bighappyworld** [comment]
did that help?

the other thing is about the location you make requests from. spam filters will mark some as not correct, but they are.

improvements on the SMTP protocol are much needed here.

additionally, where you do the search from matters. for example if you are running it on a server that is a valid email server with an MX record for the address you use with the program you have a better chance of it working.

**Comment by zh99998** [comment]
finally it's done.
yes it help, but still not enough.
i run it 2 times, result is different, combines and uniq, there is 236960 valid addresses. but each of them is about only 200k.

i'd run it again from another server and different sender & FQDN. maybe it will grow up 30k valid address again...

btw, infinite timeout is awful, it stroked after 50k results. I set a 30000ms timeout and run again then it works. consider set a timeout by default.

**Comment by bighappyworld** [comment]
ok, will consider the 30s timeout by default. there are a huge number of variables that determine whether or not the spam filters will say yes or no that the email exists. plus there are email servers that use different protocols and may not respond to the currently implemented messaging.

plus you have different versions for SMTP servers (old vs new) that will use different protocols. HELO vs EHLO as an example. this is a simple tool for a very complex issue. it could be made into a more complex tool but you still end up with other issues like an email server that says "YES" to all emails... and directs all to a specified email. the email will get delivered to A email, but no telling if it is the intended one.
