### ISSUE TITLE
Issues on some domains

### ISSUE THREAD

**Issue by kidpikoon** [bighappyworld/email-verify#23]
Hey,
Validation of all cisco.com email ids returns success always...
xyz0000@cisco.com returns success
What could be the reason ?
(Testing from AWS servers, I guess requests from local IPs get blocked)

**Comment by bighappyworld** [comment]
Try the same commands using the command-line. Or if you want, fork the repo and give me a pull-request that integrates the debug module. That may help tons of people really understand what is going on with some of the messages. More than likely it is yahoos spam filter. Lots of times they check the domain of the sending address (in our case fake) and check the MX records in the DNS. If the sending IP doesn't match the MX record in the DNS, they block it.
