### ISSUE TITLE
Email verify does not work with services that block ports like 25 like Comcast

### ISSUE THREAD

**Issue by adam-s** [bighappyworld/email-verify#29]
I'm at a loss trying to figure out how to use. I can't get Comcast or using a remote server like Heroku to make connections with email providers. I read somewhere that Amazon EC2 works for send email. The idea is that spammers are taking over personal computers and the major ISPs are preventing connections on port 25 to combat it.

**Comment by fones** [comment]
When connecting from my laptop, I always get 

`SOCKET ERROR: Error: connect ETIMEDOUT 173.194.222.27:25
{ [Error: connect ETIMEDOUT 173.194.222.27:25]
  cause: 
   { [Error: connect ETIMEDOUT 173.194.222.27:25]
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '173.194.222.27',
     port: 25 },
  isOperational: true,
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '173.194.222.27',
  port: 25 }`

**Comment by hhsadiq** [comment]
@adam-s @fones so guys were you able to solve this issue. I am also having similar issue where my small script using this module is hosted on Heroku.

Is it the case that using EC2 is way to go? Or the provider is blocking IPs because I usually check around 40 to 50 emails in a loop?

**Comment by fones** [comment]
@hhsadiq i think some inbox providers can block some range of IP's that are 100% sure not an e-mail servers. There are a lot of start-up that using this technique to get prospects e-mails, so e-mail providers are fighting with this. For me EC2 is a way to go.

**Comment by hhsadiq** [comment]
@fones hmm good point. Thanks alot.

**Comment by bighappyworld** [comment]
@fones @hhsadiq we get local provider blockage as well and also use EC2. an even more "credible" solution is if you are running the mail queries from the same IP as your actual mail server with an MX record that points to that server address. so if you ran a postfix / dovecot server for email, had all the proper mx records, dkim, etc email to make your server legit, then running the email searches from that machine should be somewhat stealthy
