### ISSUE TITLE
Some strange issue when verifying email address like xxx@hotmail.com or xxx@qq.com

### ISSUE THREAD

**Issue by viviyu** [bighappyworld/email-verify#3]
Hi bighappyworld,

Thank you for writing such a fantastic module, it's really good to help to valid email address.

However I find some strange issues when verifying email address like test@hotmail.com or test@qq.com. The script will keep loading until timeout. 

I just try to verify address like test@gmail.com, under this situation, the socket.on('data', function(data){...}) function will be called every time socket.write something. However when to verify address like test@hotmail.com or test@qq.com, the socket.on('data', function(data){...}) function won't be called after socket.write("EHLO rob\n"). 

I was testing under local environment, I'm not sure if it's the problem.

It's so good if you can help to have a look.

Hope you have a happy 2015 ^^

**Comment by bighappyworld** [comment]
great catch on this, I knew there was an issue with some mail servers but looked a bit deeper at it for you and found the problem. I used telnet and connected to hotmail to try the SMTP commands and saw the problem immediately. The EHLO rob was a problem, it needed to be a FDQN for some servers (mail.below.io). So I fixed this by adding a fdqn option to the programatic way of using this and added a -f option to the command line. Also changed the defaults to not use my name / domain and to use a fake one, so it is advised to use the -f / -sd option from the command line or the fdqn / sender option in node.
