### ISSUE TITLE
Email addresses with automatic replies set up being marked as invalid

### ISSUE THREAD

**Issue by asusventura123** [bighappyworld/email-verify#32]
I have found that email addresses which have an automatic reply set up on them (e.g. 'I am currently on leave until the DD/MON/YYYY, please contact example@example.com if you have an urgent request.') are being marked as invalid when they are not invalid, just temporarily out of use. Is there a way around this? 
Cheers,
AsusVentura

**Comment by fizerkhan** [comment]
+1

**Comment by bighappyworld** [comment]
Not a way around it, but more than likely they are configured to have a different response code that isn't being looked for. Look into the response codes and if you can figure something out, throw in a pull request with the extra response code. That sounds like a good addition.
