### ISSUE TITLE
Option for return on first success instead of searching all possibilties

### ISSUE THREAD

**Issue by fizerkhan** [bighappyworld/email-verify#34]
Is there any option for return on first success instead of waiting for all possibilities? 

        email-verify -d domain.com -n John Doe

**Comment by bighappyworld** [comment]
You could make it, but that's not a good idea. When you see ALL of them pass, you should realize that the email server has a catch-all and basically you can't really get any information about if it is good or not.

**Comment by fizerkhan** [comment]
@bighappyworld I agree with you.
