### ISSUE TITLE
Nemesis ESMTP Service not available

### ISSUE THREAD

**Issue by fizerkhan** [bighappyworld/email-verify#38]
The email verify fails because of failing error

```
root@ubuntu:~/testing# email-verify james@alpha.gg
INFO: # Veryfing james@alpha.gg
INFO: Resolving DNS... alpha.gg
INFO: MX Records {"exchange":"mx00.1and1.co.uk","priority":20}
INFO: Choosing mx00.1and1.co.uk for connection
INFO: Creating connection...
INFO: Connected
SERVER: 554-kundenserver.de (mxeue010) Nemesis ESMTP Service not available
SERVER: 554-No SMTP service
SERVER: 554 invalid DNS PTR resource record, IP=198.179.57.23
SERVER:
INFO: Closing connection
{ success: false,
  info: 'james@alpha.gg is an invalid address',
  addr: 'james@alpha.gg' }
```

I checked with other validator, they are saying that the email address is valid.

**Email Hunter**

[https://hunter.io/email-verifier/james@alpha.gg](https://hunter.io/email-verifier/james@alpha.gg)

**Comment by fizerkhan** [comment]
I fixed it by renaming digital ocean droplet's name.

**Comment by imrany** [comment]
Hi, I am also getting invalid address on a valid email address and reason being the same "perfora.net (mxeueus003) Nemesis ESMTP Service not available
No SMTP service
invalid DNS PTR resource record, IP=182.185.147.xxx"

I have tested on multiple online email verifier , and they can successfully verified that email address.

Any idea how to fix this ?

**Comment by imrany** [comment]
Hello @fizerkhan , could you please elaborate little bit more on the solution of this problem ? I am also getting this same error. I am testing it from my local machine.
