### ISSUE TITLE
valid address saying not valid

### ISSUE THREAD

**Issue by venkatadapala** [bighappyworld/email-verify#43]
root@localhost:~# email-verify technodrive104@outlook.com
{ success: false,
  info: 'technodrive104@outlook.com is an invalid address',
  addr: 'technodrive104@outlook.com' }

**Comment by thebarty** [comment]
is it only that address, or do you experience the same with others?

**Comment by venkatadapala** [comment]
for all 
Microsoft accounts

**Comment by bighappyworld** [comment]
ok so this tool works by making a TCP connection to a SMTP server and following the protocol up the point where the mail server acknowledges that the mail can be sent to the address you are requesting, then it cuts the connection.

it's plenty possible that there are different versions of the SMTP protocol implemented on different servers, that there is something missing from this tool's implementation or that they are doing more checks to see if you are an actual valid mail server.

Telnet to a SMTP server, follow the protocol in your terminal and you could probably quickly see where there is an issue... the code in the library is really simplistic, nothing fancy. if you find that the implementation in the tool is missing something, give me a pull request.

For other possibilities, like their mail server being smarter and checking to see if you are a real mail server, that one is on you to configure things on your side.
